### ISSUE TITLE
UserIds are integer in gcCreateChannel

### ISSUE THREAD

**Issue by saurabh-jadhav-theporter** [sendbird/sendbird-platform-sdk-java#2]
<!DOCTYPE html>

userIds | List of Integer | Specifies an array of one or more IDs of users to invite to the channel. The maximum number of users to be invited at once is 100. The users below and this property can be used interchangeably.
-- | -- | --

But on postman collection we can pass userid's in string

**Comment by saurabh-jadhav-theporter** [comment]
@james-a-rob Can you or anyone from team help us out here!

**Comment by tylerhammer** [comment]
@saurabh-jadhav-theporter Thank you for the report. I see you submitted a case via Support so we'll handle this there.
