### ISSUE TITLE
please upload to maven reopository

### ISSUE THREAD

**Issue by Choi-JinHwan** [sendbird/sendbird-platform-sdk-java#3]
please this library upload to maven reopository

**Comment by james-a-rob** [comment]
Thanks @Choi-JinHwan 

We are currently in the process of making this SDK available via Maven.

I am expecting the work to be completed at some point next week.

I will drop a response on this thread as soon as it is available.

**Comment by Choi-JinHwan** [comment]
Thanks
It's awesome

**Comment by james-a-rob** [comment]
Hi @Choi-JinHwan 

Just circling back here with an update.

Today we released this SDK to Maven 🚀

groupId: org.sendbird
artifactId: sendbird-platform-sdk

This is early days for this repo so if you have any issue downloading or any other issue at all then please reach out again.

Many thanks

**Comment by Jakob-MI** [comment]
@james-a-rob I was also looking for the maven release, but I am unable to find it anywhere, neither under groupid `org.sendbird` nor `org.openapitools`(the one from readme). Can you share a link to it here, or check to where it was released?
